apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: awx-operator
  pass_credentials_all: false
  password: ""
  url: https://ansible.github.io/awx-operator/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kubernetes-dashboard
  pass_credentials_all: false
  password: ""
  url: https://kubernetes.github.io/dashboard/
  username: ""
